[project]
name = "langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yujins01", email = "neosyj01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.4",
    "langchain-openai>=1.6.4",
    "langchain-text-splitters>=1.1.2",
    "openai>=3.19.0",
    "pypdf>=6.19.0",
]

[project.scripts]
langchain = "langchain:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
