# -*- coding: utf-8 -*-
"""ex0907.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15V0F0EXbWGWamRS9UYcIeKmhQwhVZywa
"""

#모듈 import
from datetime import datetime # 날짜/시간 관련 모듈
# BaseModel -> Pydantic의 데이터 검증용 부모 클래스
# positiveInt -> 0보다 큰 정수
# ValidationError -> 데이터 검증 실패 시 발생하는 에러
from pydantic import BaseModel, PositiveInt, ValidationError

# Annoted -> 타입에 추가 조건을 붙일 때 사용
# Literal -> 정해진 값만 허용할 때 사용
from typing import  Annotated, Literal
from annotated_types import Gt # ~보다 크다 라는 조건

# 클래스 선언부
# BaseModel을 상속받으면 Pydantic이 클래스 안의 데이터를 자동으로 검사
# 변수에 들어갈 데이터 타입을 정해줌
class User(BaseModel):
  id:int
  name: str = 'John Doe' #기본값으로 "John Doe"사용
  signup_ts: datetime | None
  tastes: dict[str, PositiveInt]

#실제 데이터
external_data = {
  'id': 123,
  'signup_ts': '2019-06-01 12:22', #문자열로 날짜 입력 -> Pydantic이 datetime으로 변환
  'tastes': {
      'wine': 9,
      b'cheese': 7,
      'cabbage': '1',
  },
}

#user object 생성
 #external_data의 딕셔너리의 key와 value를 클래스의 매개변수로 풀어서 전달
user = User(**external_data) 

#데이터 확인
print(user.id)
#> 123
print(user.model_dump()) # pydantic 객체를 일반 Python 딕셔너리로 변환

print(user.id)
print(user.signup_ts)
print(user.tastes)

external_data2 = {
  'id': 'not an int',
  'tastes': {}
}

try:
  User(**external_data2)
except ValidationError as e:
  print(e.errors())


#Fruit class

class Fruit(BaseModel):
  name: str
  color: Literal['red','green'] #red와 green만 허용
  weight: Annotated[float, Gt(0)] #0보다 큰 실수
  bazam: dict[str,list[tuple[int,bool,float]]]

print(
  Fruit(
      name='Apple',
      color='red',
      weight=4.2,
      bazam={'foobar': [(1, True, 0.1)]}, #튜플
  )
)

#Meeting class
class Meeting(BaseModel):
  when : datetime
  where: bytes
  why: str='No idea'

m=Meeting(when='2020-01-01', where ='home')

print(m.model_dump(exclude_unset=True))
print(m.model_dump(exclude={'where'}, mode='json'))
print(m.model_dump_json(exclude_defaults=True))